### PR TITLE
fix comple error PluginUtils::outputLog on android.

### PR DESCRIPTION
**Pull request by pyrasis**
fix comple error PluginUtils::outputLog on android.

thanks.

### CODE REVIEW

**Comment by natural-law** [comment]
@pyrasis 
Hi, what's your mean of compile error? I haven't see any error during the compiling of the PluginUtils.cpp.
Maybe there are some mistakes of your environment.

Please tell me how to reproduce the compile error. Thank you!

**Comment by pyrasis** [comment]
@natural-law 
I use Windows 8, adt-bundle-windows-x86_64-20131030, android-ndk-r9b and cygwin.

I've run publish.sh on cygwin.

```
[armeabi] Compile++ thumb: PluginProtocolStatic <= PluginUtils.cpp
jni/../../platform/android/PluginUtils.cpp: In static member function 'static void cocos2d::plugin::PluginUtils::outputLog(char const*, char const*, ...)':
jni/../../platform/android/PluginUtils.cpp:172:52: error: format not a string literal and no format arguments [-Werror=format-security]
cc1plus.exe: some warnings being treated as errors
```

thanks.

**Comment by pyrasis** [comment]
@natural-law 
Hello.

I had another test on Mac with adt-bundle-mac-x86_64-20131030, android-ndk-r9b.

I had run publish.sh on Terminal.

```
[armeabi] Compile++ thumb: PluginProtocolStatic <= PluginUtils.cpp
jni/../../platform/android/PluginUtils.cpp: In static member function 'static void cocos2d::plugin::PluginUtils::outputLog(char const*, char const*, ...)':
jni/../../platform/android/PluginUtils.cpp:172:52: error: format not a string literal and no format arguments [-Werror=format-security]
cc1plus: some warnings being treated as errors
```

Please review this issue.

**Comment by natural-law** [comment]
@pyrasis 
Thanks for your contribution. I reproduced the error when using ndk-r9c.

**Pull request merged**
